In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
page_count=1
while True:
    URL=f"https://quotes.toscrape.com/page/{page_count}/"
    res=requests.get(URL)

    soup=BeautifulSoup(res.text,"lxml")
    quotes=soup.select("div.quote")

    if not quotes:
        print("no valid pages anymore")
        break

    with open(f"scraped_data/quotes{page_count}.html","w",encoding="utf-8") as f:
        f.write(res.text)
        print(f"Downloaded data from page{page_count}")

    page_count=page_count+1

Downloaded data from page1
Downloaded data from page2
Downloaded data from page3
Downloaded data from page4
Downloaded data from page5
Downloaded data from page6
Downloaded data from page7
Downloaded data from page8
Downloaded data from page9
Downloaded data from page10
no valid pages anymore

In [20]:
#extract useful info
with open("scraped_data/quotes1.html","r",encoding="utf-8") as f:
    html_content=f.read()

soup=BeautifulSoup(html_content,"lxml")
all_quotes=soup.select("div.quote")
all_quotes

[<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
 <a class="tag" href="/tag/change/page/1/">change</a>
 <a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
 <a class="tag" href="/tag/thinking/page/1/">thinking</a>
 <a class="tag" href="/tag/world/page/1/">world</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
 <span>by <small class="author" itemprop="author">J.K. Rowling</small>
 <a href="/author/J-K-Rowling">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
 <a class="tag" href="/tag/abilities/page/1/">abilities</a>
 <a class="tag" href="/tag/choices/page/1/">choices</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/live/page/1/">live</a>
 <a class="tag" href="/tag/miracle/page/1/">miracle</a>
 <a class="tag" href="/tag/miracles/page/1/">miracles</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
 <span>by <small class="author" itemprop="author">Jane Austen</small>
 <a href="/author/Jane-Austen">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
 <a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>
 <a class="tag" href="/tag/books/page/1/">books</a>
 <a class="tag" href="/tag/classic/page/1/">classic</a>
 <a class="tag" href="/tag/humor/page/1/">humor</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>
 <span>by <small class="author" itemprop="author">Marilyn Monroe</small>
 <a href="/author/Marilyn-Monroe">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
 <a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
 <span>by <small class="author" itemprop="author">Albert Einstein</small>
 <a href="/author/Albert-Einstein">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
 <a class="tag" href="/tag/adulthood/page/1/">adulthood</a>
 <a class="tag" href="/tag/success/page/1/">success</a>
 <a class="tag" href="/tag/value/page/1/">value</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
 <span>by <small class="author" itemprop="author">André Gide</small>
 <a href="/author/Andre-Gide">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="life,love" itemprop="keywords"/>
 <a class="tag" href="/tag/life/page/1/">life</a>
 <a class="tag" href="/tag/love/page/1/">love</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>
 <span>by <small class="author" itemprop="author">Thomas A. Edison</small>
 <a href="/author/Thomas-A-Edison">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
 <a class="tag" href="/tag/edison/page/1/">edison</a>
 <a class="tag" href="/tag/failure/page/1/">failure</a>
 <a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
 <a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>
 <span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
 <a href="/author/Eleanor-Roosevelt">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
 <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>
 </div>
 </div>,
 <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
 <span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
 <span>by <small class="author" itemprop="author">Steve Martin</small>
 <a href="/author/Steve-Martin">(about)</a>
 </span>
 <div class="tags">
             Tags:
             <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
 <a class="tag" href="/tag/humor/page/1/">humor</a>
 <a class="tag" href="/tag/obvious/page/1/">obvious</a>
 <a class="tag" href="/tag/simile/page/1/">simile</a>
 </div>
 </div>]

In [56]:
author_quote=[]
for q in all_quotes:
    tags=q.select("div.tags a.tag")
    tag=[t.get_text(strip=True) for t in tags]
    if "life" in tag:
        author=(q.select_one("small.author").get_text(strip=True))
        quote=(q.select_one("span.text").get_text(strip=True))
        author_quote.append([author,quote])
    # tag_list=[t.get_text(strip=True) for t in tags]
    # print(tag_list)
print(author_quote)

[['Albert Einstein', '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”'], ['André Gide', '“It is better to be hated for what you are than to be loved for what you are not.”']]

In [47]:
import pandas as pd
df=pd.DataFrame(author_quote,columns=['Author','Quote'])
df

            Author                                              Quote
0  Albert Einstein  “There are only two ways to live your life. On...
1       André Gide  “It is better to be hated for what you are tha...

In [72]:
author_quote_list=[]

for i in range(1,page_count):
    with open(f"scraped_data/quotes{i}.html","r",encoding="utf-8") as f:
        html_content=f.read()
        
    soup=BeautifulSoup(html_content,"lxml")
    all_quotes=soup.select("div.quote")
    
    for q in all_quotes:
        tags=q.select("div.tags a.tag")
        tag=[t.get_text(strip=True) for t in tags]

        if "life" in tag:
            author=q.select_one("small.author").get_text(strip=True)
            quote=q.select_one("span.text").get_text(strip=True)
            author_quote_list.append([author,quote,tag])

quotes_dataframe=pd.DataFrame( author_quote_list,columns=["Author","Quotes","Tags"])

In [73]:
quotes_dataframe

,Author,Quotes,Tags
0,Albert Einstein,“There are only two ways to live your life. On...,"[inspirational, life, live, miracle, miracles]"
1,André Gide,“It is better to be hated for what you are tha...,"[life, love]"
2,Marilyn Monroe,“This life is what you make it. No matter what...,"[friends, heartbreak, inspirational, life, lov..."
3,Douglas Adams,"“I may not have gone where I intended to go, b...","[life, navigation]"
4,Mark Twain,"“Good friends, good books, and a sleepy consci...","[books, contentment, friends, friendship, life]"
5,Allen Saunders,“Life is what happens to us while we are makin...,"[fate, life, misattributed-john-lennon, planni..."
6,Dr. Seuss,"“Today you are You, that is truer than true. T...","[comedy, life, yourself]"
7,Albert Einstein,“Life is like riding a bicycle. To keep your b...,"[life, simile]"
8,George Bernard Shaw,“Life isn't about finding yourself. Life is ab...,"[inspirational, life, yourself]"
9,Ralph Waldo Emerson,“Finish each day and be done with it. You have...,"[life, regrets]"
10,Mark Twain,“The fear of death follows from the fear of li...,"[death, life]"
11,Jimi Hendrix,“I'm the one that's got to die when it's time ...,"[death, life]"
12,Khaled Hosseini,“But better to get hurt by the truth than comf...,[life]